
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://CMUSoundbytes.github.io/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: #"/Soundbytes"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Daniel Graf"
title: "Soundbytes"
description: "Everything about the Carnegie Mellon Soundbytes. Fun times had by all."
keywords: "soundbytes, carnegie, mellon, music, acapella"
favicon: "/img/soundbytesfavicon.png"

################
# Header layout #
################

black-favicon: "/img/mainlogowhite.png"

background-img: "../img/mainphoto.jpg"

##############################
# Dynamic Text on the Header #
##############################

#dynamic-typing: True
#shuffle: True # Shuffle the lines.
#loop: True
#loop-count: False # Set False for infinite loop, or set any number for finite loop.
#type-speed: 10
#start-delay: 200
#delete-delay: 5000
#lines: # You can add HTML Tags in the Text
#  - text: "The lower you fall, the higher you'll fly."
#  - text: "Whereâ€™s your will to be weird?"
#  - text: "Why am I awesome?"
#  - text: "This is procrastinating"
#  - text: "Someone help me"
#  - text: "Oops..."
#  - text: "Normally I'm last"

me-img: "/img/mainlogo2.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

#disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

#events:
#  - image: "/img/timeline/spidertocat.png"
#    date: "September 2013 - Today"
#    description: "Saving the neighborhood!"
#  - image: "/img/timeline/baracktocat.jpg"
#    date: "September 2007 - August 2013"
#    description: "Started coding"
#
## First image of the Timeline
#
#timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "cmusoundbytes@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Daniel Graf is an awesome person. He is a senior, and by the time you read this, he will probably be gone."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/cmusoundbytes/?fref=ts"
  - title: "instagram"
    url: "https://www.instagram.com/cmusoundbytes/"
  - title: "youtube"
    url: "http://www.youtube.com/user/cmusoundbytes"
  - title: "envelope"
    url: "mailto:cmusoundbytes@gmail.com"

############
# 404 page #
############

404-img: "/img/largelogo.png"

##################
# GPG on Keybase #
##################

keybase-username: none
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Performances: 'latest-post'
  Members: 'member-list'
  Contact: 'contact'
  
# List of active members
 
members_list:
#Sopranos
  leah: 
    name: 'Leah Anton'
    section: 'Soprano'
    pic: "/img/members/sopranos/leah/leah1-MAIN-test.jpg"
  catherine: 
    name: 'Catherine Mondoa'
    section: 'Soprano'
    pic: "/img/members/sopranos/catherine/catherine4-MAIN-test.jpg"
  shreya: 
    name: 'Shreya Desikan'
    section: 'Soprano'
    pic: "/img/members/sopranos/shreya/shreya4-MAIN-test.jpg"
  zoe: 
    name: 'Zoe Lehn'
    section: 'Soprano'
    pic: "/img/members/sopranos/zoe/zoe2-MAIN-test.jpg"
  lexi: 
    name: 'Alexis De La Rosa'
    section: 'Soprano'
    pic: "/img/members/sopranos/lexi/lexi1-MAIN-test.jpg"
#Altos
  toby: 
    name: 'Toby Donoghue'
    section: 'Alto'
    pic: "/img/members/altos/toby/toby1-MAIN-test.jpg"
  sarah: 
    name: 'Sarah Karp'
    section: 'Alto'
    pic: "/img/members/altos/sarah/sarah1-MAIN-test.jpg"
  angela: 
    name: 'Angela Yoo'
    section: 'Alto'
    pic: "/img/members/altos/angela/angela2-MAIN-test.jpg"
  christina: 
    name: 'Christina Cabana'
    section: 'Alto'
    pic: "/img/members/altos/christina/christina1-MAIN-test.jpg"
  christie: 
    name: 'Christie Chang'
    section: 'Alto'
    pic: "/img/members/altos/christie/christie4-MAIN-test.jpg"

#Tenors
  quinton: 
    name: 'Quinton Laurencio'
    section: 'Tenor'
    pic: "/img/members/tenors/q/Q4-MAIN-test.jpg"
  johnathan: 
    name: 'Johnathan Roppo'
    section: 'Tenor'
    pic: "/img/members/tenors/johnathan/johnathan4-MAIN-test.jpg"
  jesse: 
    name: 'Jesse Klein'
    section: 'Tenor'
    pic: "/img/members/tenors/jesse/jesse3-MAIN-test.jpg"
  matthew: 
    name: 'Matthew Gutierrez'
    section: 'Tenor'
    pic: "/img/members/tenors/matthew/matthew1-MAIN-test.jpg"
  steven: 
    name: 'Steven MacDonald'
    section: 'Tenor'
    pic: "/img/members/tenors/steven/steven1-MAIN-test.jpg"
  philip: 
    name: 'Philip DeCicco'
    section: 'Tenor'
    pic: "/img/members/tenors/phil/phil4-MAIN-test.jpg"
  

#Basses
  daniel: 
    name: 'Daniel Graf'
    section: 'Bass'
    pic: "/img/members/basses/daniel/daniel2-test.jpg"
  paul: 
    name: 'Paul Rogozenski'
    section: 'Bass'
    pic: "/img/members/basses/paul/paul5-MAIN-test.jpg"
  nikhil: 
    name: 'Nikhil Nilakantan'
    section: 'Bass'
    pic: "/img/members/basses/daniel/daniel2-test.jpg"
  jack: 
    name: 'Jack Urbanek'
    section: 'Bass'
    pic: "/img/members/basses/jack/jack1-MAIN-test.jpg"
  sean: 
    name: 'Sean Park'
    section: 'Bass'
    pic: "/img/members/basses/sean/sean3-MAIN-test.jpg"
  
  
# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
